name: ci

# Workflow will run when there are commits to the `main` branch
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  dockerfile-lint:
    name: Dockerfile Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  docker-hub:
    name: Build and Push to Docker Hub
    needs: [dockerfile-lint]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        env:
          DOCKERHUB_REPO: alexsam29/fragments-ui
          SHA_TAG: sha-${{ github.sha }}
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:${{ env.SHA_TAG }}, ${{ env.DOCKERHUB_REPO }}:main, ${{ env.DOCKERHUB_REPO }}:latest
